# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Abdel Raoof'
tagline:          'Tangled web dairy of Abdel Raoof'
description:      'This is personal site of Abdel Raoof Olakara'
url:              'http://abdelraoof.com'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
#- text: Search
#  url: /search/


# Author Details
author:         'Abdel Raoof Olakara'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/olakara'
flickr:
github:         'https://github.com/olakara'
gplus:          'https://plus.google.com/100425464897246255887/'
instagram:
pinterest:
linkedin:       'https://ae.linkedin.com/in/olakara/'
rss:
stackoverflow:  'http://stackoverflow.com/users/185655/abdel-raoof'
twitter:        'https://twitter.com/olakara'

# Google Analytics
gahandler: 'UA-53220404-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'abdelraoof'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2 (custom)
